name: Format Check

# Run on all push and pull requests
on:
  push:
  pull_request:

jobs:
  format-check:
    name: Check Format
    uses: astrogeco/cFS/.github/workflows/format-check.yml@update-clang-format